---
title: "Lab02"
author: "Brian Sayre"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Get the data.

```{r}
choco <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/data/choco.csv") 
str(choco) 
```


1.  
```{r}
hist(choco$Rating)
```

```{r}
boxplot(choco$Rating)
```
  
2.  
```{r}
library(ggplot2)
t <- table(choco$Location)
barplot(t)
```
  
3.  
```{r}
plot(choco$Rating, choco$Cocoa_Percent)
```

```{r}
cor(choco$Cocoa_Percent, choco$Rating)
```

```{r}
agg <- aggregate(choco$Rating, by=list(choco$Cocoa_Percent), FUN=mean)
plot(agg)
```

5.

```{r}


t <- table(choco$Characteristics1)
charDF <- as.data.frame(t) 
charDF
data <- charDF[order(charDF$Freq),]
data

creamy <- choco[choco$Characteristics1 == "creamy",]
creamyMean <- mean(creamy$Rating)
print(creamyMean)
loc <- table(creamy$Bean_Origin)
locDF <- as.data.frame(loc) 
data <- locDF[order(locDF$Freq),]
tail(data, 3)

sandy <- choco[choco$Characteristics1 == "sandy",]
sandyMean <- mean(sandy$Rating)
print(sandyMean)
loc <- table(sandy$Bean_Origin)
locDF <- as.data.frame(loc) 
data <- locDF[order(locDF$Freq),]
tail(data, 3)
 
intense <- choco[choco$Characteristics1 == "intense",]
intenseMean <- mean(intense$Rating)
print(intenseMean)
loc <- table(intense$Bean_Origin)
locDF <- as.data.frame(loc) 
data <- locDF[order(locDF$Freq),]
data
tail(data, 3)


```