<h1>Question 1</h1>
```{r}
choco <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/data/choco.csv") 
str(choco) 
```

```{r}
library('ggplot2')
head(choco)
```
```{r}
hist(choco$Rating)
```
```{r}
boxplot(choco$Rating)
```

<h1>Question 2</h1>
```{r}
t <- table(choco$Location)
barplot(t)
```

<h1>Question 3</h1>

```{r}
correlation <- cor(choco$Cocoa_Percent, choco$Rating)
correlation

#For this we took the average rating and grouped it by the cocoa_percent
#Without modifying the data how we did the plot would give useless data of dots in lines.
agg1 = aggregate(choco$Rating, by=list(choco$Cocoa_Percent), FUN=mean)
agg1

plot(agg1)

#For this we did the same as above but in reverse
agg2 = aggregate(choco$Cocoa_Percent, by=list(choco$Rating), FUN=mean)
agg2

plot(agg2)
``` 

<h1>Question 4</h1>

<h1>Question 5</h1>
```{r}
#Cocoa Percent by Company
agg3 = aggregate(choco$Cocoa_Percent, by=list(choco$Company), FUN=length)
agg3

pie(unique(choco$Cocoa_Percent))
```